
version: '3'

services:
  deno-app:
    build: .
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo_db:/data/db
